### ISSUE TITLE
SASSIFI

### ISSUE THREAD

**Issue by yuehs1994** [NVlabs/sassifi#6]
Hi Dr. Hari,
 
I am Hengshan Yue, a PhD student from Jilin University, China. Currently I am trying to use your SASSIFI tool for GPU fault injection experiments in Rodinia benchmarks. The benchmarks from Rodinia suite all require some complex input data files, and execution results are stored into output files instead of printing on the screen. However, the simple_add example in SASSIFI does not require any input or output file in the Makefile. I am wondering how should I modify SASSIFI to support fault injections for Rodinia benchmarks? i.e., how should I modify the makefile in a benchmark and how should I modify SASSIFI source code to compare the “faulty run results” with the “golden run”? I saw your IISWC’17 paper uses SASSIFI on some Rodinia benchmarks as well. So, could you send me some example makefile, application-specific scripts, etc. for Rodinia benchmarks to run in SASSIFI if possible?
 
I really appreciate your help!I also sent you an email.
 
Thanks,
Hengshan

**Comment by sivahari** [comment]
Hi Hengshan,

Comments in the sample [sdc_check.sh](https://github.com/NVlabs/sassifi/blob/master/run/example/simple_add/sdc_check.sh) script (lines 2-7) explain how to handle outputs generated by a program that's not captured in stdout/stderr. Specifically, lines 9-10 and 25-28 explain what exactly to do with such files.

For example, gaussian workload from Rodinia 2.3 generates solution.txt. We collect the golden solution.txt by running the program without any errors. (If the program uses a random number generator, we want to fix the seed so that the outputs are deterministic.) So, we want to replace line 11 in [sdc_check.sh](https://github.com/NVlabs/sassifi/blob/master/run/example/simple_add/sdc_check.sh#L11) with the following. 
diff solution.txt /full/path/to/golden_solution.txt > diff.log

This program also prints runtimes in stdout. We want to exclude that when we compare stdout because runtimes vary from run to run by modifying [line 19](https://github.com/NVlabs/sassifi/blob/master/run/example/simple_add/sdc_check.sh#L19) as follows:
diff  -I "^Time*" clean_stdout.txt /full/path/to/golden_stdout.txt > stdout_diff.log

If you do not want application specific checking, you can comment out all lines after [line 25](https://github.com/NVlabs/sassifi/blob/master/run/example/simple_add/sdc_check.sh#L25).

To prepare the workload, you need to modify the Makefile similar to include EXTRA_NVCC_FLAGS and EXTRA_LINK_FLAGS as shown in the [example Makefile](https://github.com/NVlabs/sassifi/blob/master/suites/example/simple_add/Makefile#L62).

I hope this helps. If you have specific questions, feel free to open this issue again. 

Siva

**Comment by yuehs1994** [comment]
Hi Dr. Hari,
Thanks for your help. I modified some makefiles as you suggested, and benchmarks with only one source file (.cu file) worked in this way. However, all benchmarks with multiple source files failed. 
 
Here is how I modified the makefile of k-means (from Rodinia version 3.1)
 
$(TARGET): cluster.o getopt.o kmeans.o kmeans_clustering.o kmeans_cuda.o rmse.o
       $(CC) $(CC_FLAGS) cluster.o getopt.o kmeans.o kmeans_clustering.o kmeans_cuda.o rmse.o -o kmeans - L/usr/local/cuda/lib64 -lcuda -lcudart -lm
 
%.o: %.[ch]
       $(CC) $(CC_FLAGS) $< -c
 
kmeans_cuda.o: kmeans_cuda.cu
       $(NVCC) -c kmeans_cuda.cu $(NVCC_FLAGS) -L$(CUDA_LIB_DIR)       $(LINK_FLAGS).
 It failed with “make OPTION=profiler/rf injector/...” command with the following error:
ptxas error   : Undefined reference to '_Z20sassi_before_handlerP17SASSIBeforeParamsP17SASSIMemoryParamsP19SASSIRegisterParams' in '<ptx>'
ptxas info    : 2455 bytes gmem, 4352 bytes cmem[3]
ptxas info    : Compiling entry function '_Z14invert_mappingPfS_ii' for 'sm_50'
ptxas info    : Function properties for _Z14invert_mappingPfS_ii
    240 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 14 registers, 344 bytes cmem[0]
ptxas info    : Compiling entry function '_Z11kmeansPointPfiiiPiS_S_S0_' for 'sm_50'
ptxas info    : Function properties for _Z11kmeansPointPfiiiPiS_S_S0_
    256 bytes stack frame, 12 bytes spill stores, 8 bytes spill loads
ptxas info    : Used 16 registers, 380 bytes cmem[0], 1 textures
make: *** [kmeans_cuda.o] Error 255
BTW, I can compile it using the default "make" option after this modification. So I think the error is caused by the fault injection part.
Do you know how to solve this error?
I also sent you an e-mail.which have my makefile.
Thanks
